version: 0.2

phases:
  build:
    commands: 
      - mkdir build
      - cd build
      - wget https://bvdc2uahu2.execute-api.us-west-2.amazonaws.com/staging/route/FF7
artifacts:
  files:
    - 'build/**/*'
  name: build-$(date +%Y-%m-%d)