version: 0.2

phases:
  build:
    commands: 
      - mkdir build
      - cd build
      - wget $(staging_api)/route/FF7
      - wget $(staging_api)/route/FF1
artifacts:
  files:
    - 'build/**/*'
  name: build-$(date +%Y-%m-%d)